# GENERAL
CAPTION = "Game"
FPS = 60
BACKGROUND_COLOUR = (255, 255, 255)
SCREEN_WIDTH = 1056
SCREEN_HEIGHT = 594
SCREEN_BORDER_MULTIPLIER = 0.1

# FILE PATHS
DATABASE_PATH = "data/database.json"
IMAGES_PATH = "data/images"
SCREENSHOT_PATH = "screenshots"
BACKGROUND_MUSIC_PATH = "data/music/Naruto Shippuden Opening 5.mp3"

# NETWORK SETTINGS
HOST = "localhost"
PORT = 5678
DATA_SIZE = 2048 * 1
MAXIMUM_NUM_CONNECTIONS = 10

# PLAYER SETTINGS
PLAYER_WIDTH = 60
PLAYER_HEIGHT = 60
PLAYER_SPEED = 4
PLAYER_SPAWN_GAP = 0.1 # Minimum distance from boundary via multiplier of screen size
PLAYER_ID_RANGE = 1023

# CROSSHAIR SETTINGS
CROSSHAIR_WIDTH = 40
CROSSHAIR_HEIGHT = 40

# JUTSU SETTINGS
JUTSU_COLOUR = (0, 0, 255)
JUTSU_ID_RANGE = 1023
DEFAULT_ACTIVATED_JUTSU = "fireball_jutsu"

# MUSIC SETTINGS
DEFAULT_VOLUME = 0.1
