# GENERAL
CAPTION = "Game"
FPS = 60
BACKGROUND_COLOUR = (255, 255, 255)
SCREEN_WIDTH = 1056
SCREEN_HEIGHT = 594

# FILE PATHS
SCREENSHOT_PATH = "screenshots"
IMAGES_PATH = "data/images"

# NETWORK SETTINGS
HOST = "localhost"
PORT = 5678
DATA_SIZE = 2048 * 1
MAXIMUM_NUM_CONNECTIONS = 10

# PLAYER SETTINGS
PLAYER_WIDTH = 60
PLAYER_HEIGHT = 60
PLAYER_SPEED = 4
PLAYER_SPAWN_GAP = 0.1 # Minimum distance from boundary via multiplier of screen size

# CROSSHAIR SETTINGS
CROSSHAIR_WIDTH = 40
CROSSHAIR_HEIGHT = 40
