# GENERAL
CAPTION = "Game"
FPS = 60
BACKGROUND_COLOUR = (255, 255, 255)
SCREEN_WIDTH = 1052
SCREEN_HEIGHT = 592

# FILE PATHS
SCREENSHOT_PATH = "screenshots"

# NETWORK SETTINGS
HOST = "localhost"
PORT = 5678
DATA_CAP = 2048 * 1

# PLAYER SETTINGS
PLAYER_WIDTH = 30
PLAYER_HEIGHT = 30
PLAYER_SPEED = 4
PLAYER_SPAWN_GAP = 0.1 # Minimum distance from boundary via multiplier of screen size
